url: https://nathanwhelan.com
baseurl: ''

# Site settings
title: "Nathan's Research"
email: nathan.whelan@gmail.com
description: "Nathan Whelan's Research Page."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: 1062ee
  primary: 1e60d2
  secondary: 3173e3 
  secondary-dark: 000
  
# Team names, titles and social links
people:
- name: Nathan Whelan
  pic: Whelan
  position: Lab Director and Principal Investigator
  description: CV available <a href="/assets/Whelan_CV_website.pdf">here</a>.
  social:
    - url: https://twitter.com/polarfire
      icon: fab fa-twitter
    - url: https://scholar.google.com/citations?hl=en&user=KQ9B0csAAAAJ
      icon: fab fa-google
    - url: https://github.com/NathanWhelan/
      icon: fab fa-github

- name: Ashantye' Williams
  pic: Ashantye
  position: Lab Manager
  description: Conservation genomics and genetic management of aquatic organisms.
  social:
    - title: google-plus
      url: https://scholar.google.com/citations?user=6QPWdO8AAAAJ&hl=en&oi=ao
      
- name: Nick Gladstone
  pic: Gladstone
  position: Ph.D. Student
  description: Evolution of life history behaviors and shell shape in freshwater gastropods. See more <a href="https://nsgladstone.weebly.com/">here</a>.  
  social:
    - title: twitter
      url: https://twitter.com/gladstone_scott
    - title: google-plus
      url: https://scholar.google.com/citations?user=Z1u8U34AAAAJ&hl=en&oi=sra
      
- name: Nicole Garrison (alum)
  pic: Garrison
  position: Postdoc
  description: Conservation genomics of freshwater mussels. See more <a href="https://westliberty.edu/biology/faculty/nicole-garrison/">here</a>.  
  social:
    - title: google-plus
      url: https://scholar.google.com/citations?user=wkOzAwgAAAAJ&hl=en&oi=ao

- name: Aaliyah Wright (alum)
  pic: Wright
  position: Undergraduate Researcher (2019 REU Student)
  description: Conservation genomics of <i>Leptoxis compacta</i>.   

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: twitter
      url: https://twitter.com/polarfire
    - title: google-plus
      url: https://scholar.google.com/citations?hl=en&user=KQ9B0csAAAAJ
    - title: github
      url: https://github.com/NathanWhelan/

# Postal address (add as many lines as necessary)
address:
  - line: 203 Swingle Hall
  - line: Auburn, AL 36801

# Build settings
markdown: kramdown
permalink: pretty
