url: https://y7kim.github.io
baseurl: ''

# Site settings
title: "Nathan's Research"
email: nathan.whelan@gmail.com
description: "Nathan Whelan's Research Page."

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: fed136
  secondary: fec503 
  secondary-dark: 000
  
# Team names, titles and social links
people:
- name: Nathan Whelan
  pic: 1
  position: Director
  social:
    - title: twitter
      url: https://twitter.com/polarfire
    - title: google-plus
      url: https://scholar.google.com/citations?hl=en&user=KQ9B0csAAAAJ
    - title: github
      url: https://github.com/NathanWhelan/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
